### ISSUE TITLE
spi on ubuntu.. error

### ISSUE THREAD

**Issue by Zibri** [hidden-refuge/spi#12]
Your desired username: Zibri
htpasswd: cannot create file /etc/squid3/passwd
/etc/squid3/squid.conf: No such file or directory
cp: cannot stat '/etc/init/squid3.conf': No such file or directory
touch: cannot touch '/etc/squid3/blacklist.acl': No such file or directory
Failed to restart squid3.service: Unit squid3.service not found.
# Generated by iptables-save v1.6.1 on Fri Jul 27 05:37:14 2018

it worked after making a link:

ln -s /etc/squid /etc/squid3

so just change the script to point to /etc/squid instead of /etc/squid3

**Comment by fdterr** [comment]
Also having this issue

I can create the directory /etc/squid3 - that gets me past the first error, but then I get the following output:

``--2018-10-21 05:30:36--  https://raw.githubusercontent.com/hidden-refuge/squid-proxy-installer/master/spi-ubuntu.conf
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.20.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.20.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2252 (2.2K) [text/plain]
Saving to: ‘/etc/squid3/squid.conf’

/etc/squid3/squid.c 100%[===================>]   2.20K  --.-KB/s    in 0s

2018-10-21 05:30:36 (15.7 MB/s) - ‘/etc/squid3/squid.conf’ saved [2252/2252]

cp: cannot stat '/etc/init/squid3.conf': No such file or directory
Failed to restart squid3.service: Unit squid3.service not found.
# Generated by iptables-save v1.6.1 on Sun Oct 21 05:30:37 2018
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p tcp -m tcp --dport 3128 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3128 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3128 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3128 -j ACCEPT
-A INPUT -i tun0 -j ACCEPT
-A INPUT -i ens3 -p udp -m udp --dport 1194 -j ACCEPT
-A FORWARD -i ens3 -o tun0 -j ACCEPT
-A FORWARD -i tun0 -o ens3 -j ACCEPT
COMMIT
# Completed on Sun Oct 21 05:30:37 2018
# Generated by iptables-save v1.6.1 on Sun Oct 21 05:30:37 2018
*nat
:PREROUTING ACCEPT [43966:2438923]
:INPUT ACCEPT [43964:2438241]
:OUTPUT ACCEPT [528:40859]
:POSTROUTING ACCEPT [528:40859]
-A POSTROUTING -s 10.8.0.0/24 -o ens3 -j MASQUERADE
COMMIT
# Completed on Sun Oct 21 05:30:37 2018``

**Comment by hidden-refuge** [comment]
Things changed in recent Ubuntu versions including directories of Squid. I merged a pull request that fixes the issues accordingly. Thanks for the contribution guys :) .
