### ISSUE TITLE
warning: empty ACL: acl siteblacklist dstdomain "/etc/squid/blacklist.acl"

### ISSUE THREAD

**Issue by denel23** [hidden-refuge/spi#16]
warning: empty ACL: acl siteblacklist dstdomain "/etc/squid/blacklist.acl"
authorization failed
How to solve the two problems, thank you

**Comment by hidden-refuge** [comment]
This is only a warning and the warning message is quite clear, isn't it? The ACL is simply empty because no sites are blocked by default unless you add one. There is no issue here.
