### ISSUE TITLE
No Such File or Directory

### ISSUE THREAD

**Issue by mrmark0123** [hidden-refuge/spi#3]
So everything was going ok, I entered my Username, but then it said, 

https://gyazo.com/d177417ed3f0ffe2413f2b7f9861c58b

**Comment by hidden-refuge** [comment]
Sorry for the very late reply. 

Which OS are you using? And which parameter did you use for installation?

**Comment by liondancer** [comment]
I am getting the same thing. I am getting

```
htpasswd: cannot create file /etc/squid3/passwd
/etc/squid3/squid.conf: No such file or directory
cp: cannot stat '/etc/init/squid3.conf': No such file or directory
touch: cannot touch '/etc/squid3/blacklist.acl': No such file or directory
Failed to restart squid3.service: Unit squid3.service not found.
# Generated by iptables-save v1.6.0 on Thu Apr 27 00:44:42 2017
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p tcp -m tcp --dport 3128 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3128 -j ACCEPT
COMMIT
# Completed on Thu Apr 27 00:44:42 2017

```
I am using ubuntu

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by hidden-refuge** [comment]
It seems like a new function from Ubuntu 16.04 is necessary. Old versions actually still do have that squid3 folder like in Debian. So it's not as easy as @3kwa makes it because atleast I still want also to support older versions of OSs in order to make this script universal.

**Comment by hidden-refuge** [comment]
Fix coming soon.
