### ISSUE TITLE
ACL mod for multiple outbound IP

### ISSUE THREAD

**Issue by MichaelRC** [hidden-refuge/spi#5]
If I wanted to amend, within the rhel7 file, this to be able to support multiple outbound connections from a single client I can I just add to the acl with something like this: 

http_port 7x.xxx.209.258:3128 name=3128
http_port 7x.xxx.120.28:3129 name=3129
http_port 7x.xxx.149.70:3130 name=3130

acl mike3128 myportname 3128 src 24.xxx.210.0/24
http_access allow mike3128
tcp_outgoing_address 67.xxx.108.128 mike3128
acl mike3129 myportname 3129 src 24.xxx.210.0/24
http_access allow mike3129

OR

act ip1 myip 1.2.3.4 
act ip2 myip 1.2.3.5 

where 1.2.3.4/5 are the server IP's and using all other portions of the script the same?

**Comment by hidden-refuge** [comment]
Hey,

I never done this actually but Google says that your code should work:
- https://www.tastyplacement.com/squid-proxy-multiple-outgoing-ip-addresses

**Comment by MichaelRC** [comment]
I found out you don't even need to do that. How it is now works perfect for
what I needed!

**Comment by David-Kurniawan** [comment]
Hi @MichaelRC 

can you share your squid.conf file please ?
i need this too

**Comment by MichaelRC** [comment]
I'll need to look for it I'm unsure if I still have it
