### ISSUE TITLE
Mehrere IPv6 Proxies auf einem Server

### ISSUE THREAD

**Issue by amster93** [hidden-refuge/spi#7]
Hey,

cooles script danke! Kann man denn auch mehr als einen ipv6 proxy auf einem Server installieren?

Habe da ein ähnliches Video gesehen:
https://www.youtube.com/watch?v=9zuw8ZIeXVo

LG

**Comment by hidden-refuge** [comment]
Squid hat keine Clustering Möglichkeiten oder ähnliches. Man kann jedoch mehrere IPv6 Adressen dem Server zuteilen und dann in Squid ein IP Rotate einrichten, so dass Squid immer die ausgehende IPv6 Adresse ändert (funktioniert auch bei IPv4 wenn man mehrere Adressen hat).

Guck mal hier: https://wiki.squid-cache.org/ConfigExamples/Strange/RotatingIPs
